services:
  web:
    container_name: pbatish_fast_api_app
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: ".env"
    environment:
      - PYTHONUNBUFFERED=1
